CVwebsite/urls.py
from blog.feeds import LatestEntriesFeed
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import path, include
from home.sitemap import StaticViewSitemap

sitemaps = {'static': StaticViewSitemap, }

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('about/', include('about.urls')),
    path('contact/', include('contact.urls')),
    path('blog/', include('blog.urls')),
    path('accounts/', include('allauth.urls')),
    path('robots.txt', include('robots.urls'), ),
    path('rss/feed/', LatestEntriesFeed()),
    path('summernote/', include('django_summernote.urls'), ),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += [
    path('captcha/', include('captcha.urls')),
]

blog/urls.py
from django.urls import path

from blog.views import blog, single_blog
from blog.sitemap import BlogSitemap

sitemaps = {'blog': BlogSitemap}
app_name = 'blog'

urlpatterns = [
    path('', blog, name='weblog'),
    path('<int:post_id>/', single_blog, name='singleblog'),
    path('category/<str:cat_name>/', blog, name='category'),
    path('author/<str:author_user>/', blog, name='author'),
    path('search/', blog, name='search'),

    path('tag/<str:tag_name>/', blog, name='tag'),
]

blog/models.py
from audioop import reverse
from taggit.managers import TaggableManager
from django.db import models
from django.contrib.auth.models import User


# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=100, null=True)

    def __str__(self):
        return self.name


class Post(models.Model):
    image = models.ImageField(upload_to='blog/', default='blog/default.jpg')
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    title = models.CharField(max_length=100)
    content = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    category = models.ManyToManyField(Category)
    published_date = models.DateTimeField(blank=True, null=True)
    status = models.BooleanField(default=False)
    count_views = models.IntegerField(default=0)
    tags = TaggableManager()

    class Meta:
        ordering = ['-created_date']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:singleblog', kwargs={'post_id': self.id})


class Comment(models.Model):
    name = models.CharField(max_length=255)
    email = models.EmailField()
    subject = models.CharField(max_length=255)
    message = models.TextField()
    approved = models.BooleanField(default=False)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

blog/forms.py
from blog.models import Comment
from django import forms


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = '__all__'

blog/views.py
from django.http import Http404
from django.utils import timezone
from django.contrib import messages
from django.shortcuts import render, get_object_or_404
from blog.forms import CommentForm
from blog.models import Post, Comment
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage


# Create your views here.


def blog(request, **kwargs):
    posts = Post.objects.filter(status=True, published_date__lte=timezone.now())
    if kwargs.get('cat_name') is not None:
        posts = posts.filter(category__name=kwargs['cat_name'])
    if kwargs.get('author_user') is not None:
        posts = posts.filter(author__username=kwargs['author_user'])
    if kwargs.get('tag_name') is not None:
        posts = posts.filter(tags__name__in=kwargs['tag_name'])

    posts = Paginator(posts, 3)
    try:
        page_numb = request.GET.get('page')
        posts = posts.get_page(page_numb)
    except PageNotAnInteger:
        posts = posts.get_page(1)
    except EmptyPage:
        posts = posts.get_page(1)

    context = {'posts': posts}
    return render(request, 'blog/blog.html', context)


def single_blog(request, post_id):
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your Comment Sent Successfully')
        else:
            messages.error(request, 'There was an error, Please try again')
    else:
        form = CommentForm()
    posts = Post.objects.filter(status=True, published_date__lte=timezone.now())
    post = get_object_or_404(posts, pk=post_id)
    post.count_views += 1
    post.save()
    current_post = Post.objects.get(pk=post_id)
    related_posts = Post.objects.filter(status=True, published_date__lte=timezone.now())
    next_post = related_posts.filter(id__gt=current_post.id).order_by('id').first()
    prev_post = related_posts.filter(id__lt=current_post.id).order_by('-id').first()
    comments = Comment.objects.filter(approved=True, post=post.id)
    context = {
        'post': post,
        'next_post': next_post,
        'prev_post': prev_post,
        'comments': comments,
        'form': form,
    }

    return render(request, 'blog/single-blog.html', context)


def blog_search(request):
    posts = Post.objects.filter(status=True, published_date__lte=timezone.now())
    if request.method == 'GET':
        posts = posts.filter(title__contains=request.GET.get('s'))
    context = {'posts': posts}
    return render(request, 'blog/blog.html', context)

templates/blog/tags/blog_categorie.html
{% load static %}

<section class="blog_categorie_area">
            <div class="container">
                <div class="row">
                    {% for post in posts %}
                    <div class="col-lg-4">
                        <div class="categories_post">
                            <img src="{{ post.image.url }}" alt="post">
                            <div class="categories_details">
                                <div class="categories_text">
                                    <a href="{% url 'blog:singleblog' post_id=1 %}"><h5>{{ post.title }}</h5></a>
                                    <div class="border_line"></div>
                                    <p>{{ post.content|truncatewords:6 }}</p>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </section>

templates/blog/tags/home_blog.html
                    {% for post in posts %}

                        <div class="categories_post">
                            <img src="{{ post.image.url }}" alt="post">
                            <div class="categories_details">
                                <div class="categories_text">
                                    <a href="{% url 'blog:singleblog' post_id=post.id %}"><h5>{{ post.title }}</h5></a>
                                    <div class="border_line"></div>
                                    <p>{{ post.content|truncatewords:6 }}</p>
                                    <div class="border_line"></div>
                                    <ul class="categories">
                                        {% for cat in post.category.all %}
                                        <li>
                                            <a href="{% url 'blog:category' cat_name=cat.name %}" class="d-flex justify-content-between">
                                                <p>{{ cat.name }}</p>
                                            </a>
                                        </li>
                                             {% endfor %}
                                    </ul>
                                </div>
                            </div>
                        </div>

                    {% endfor %}

templates/blog/tags/last_post.html
{% load static %}
{% load humanize %}
                            <aside class="single_sidebar_widget popular_post_widget">
                                <h3 class="widget_title">Popular Posts</h3>
                                {% for post in posts %}
                                <div class="media post_item">
                                    <img class="img-fluid sidebar-post" src="{{ post.image.url }}" alt="post">
                                    <div class="media-body">
                                        <a href="{% url 'blog:singleblog' post_id=post.id %}"><h3>{{ post.title }}</h3></a>
                                        <p>{{ post.published_date|naturaltime }}</p>
                                    </div>
                                </div>
                                {% endfor %}
                            </aside>

templates/blog/tags/post_categories.html
{% load blog_tag %}
{% load static %}



                            <aside class="single_sidebar_widget post_category_widget">
                                <h4 class="widget_title">Post Catgories</h4>
                                <ul class="list cat-list">
                                    {% for name,count in category.items %}
                                    <li>
                                        <a href="{% url 'blog:category' cat_name=name %}" class="d-flex justify-content-between">
                                            <p>{{ name }}</p>
                                            <p>{{ count }}</p>
                                        </a>
                                    </li>
                                    {% endfor %}
                                </ul>
                                <div class="br"></div>
                            </aside>

templates/blog/tags/search_bar.html
{% load static %}
<aside class="single_sidebar_widget search_widget">
    <div class="input-group">
        <form class="search-form" action="{% url 'blog:search' %}" method="get">
            <label>
                <input class="form-control" placeholder="Search Posts" name="s" type="text" >
            </label>
            <span class="input-group-btn">
            <button type="button" class="btn btn-default"><i class="lnr lnr-magnifier"></i></button>
            </span>
        </form>
    </div>
    <div class="br"></div>
</aside>