CVwebsite/urls.py
from blog.feeds import LatestEntriesFeed
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import path, include
from home.sitemap import StaticViewSitemap

sitemaps = {'static': StaticViewSitemap, }

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('about/', include('about.urls')),
    path('contact/', include('contact.urls')),
    path('blog/', include('blog.urls')),
    path('accounts/', include('allauth.urls')),
    path('robots.txt', include('robots.urls'), ),
    path('rss/feed/', LatestEntriesFeed()),
    path('summernote/', include('django_summernote.urls'), ),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += [
    path('captcha/', include('captcha.urls')),
]

blog/urls.py
from django.urls import path

from blog.views import blog, single_blog
from blog.sitemap import BlogSitemap

sitemaps = {'blog': BlogSitemap}
app_name = 'blog'

urlpatterns = [
    path('', blog, name='weblog'),
    path('<int:post_id>/', single_blog, name='singleblog'),
    path('category/<str:cat_name>/', blog, name='category'),
    path('author/<str:author_user>/', blog, name='author'),
    path('search/', blog, name='search'),

    path('tag/<str:tag_name>/', blog, name='tag'),
]

blog/models.py
from audioop import reverse
from taggit.managers import TaggableManager
from django.db import models
from django.contrib.auth.models import User


# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=100, null=True)

    def __str__(self):
        return self.name


class Post(models.Model):
    image = models.ImageField(upload_to='blog/', default='blog/default.jpg')
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    title = models.CharField(max_length=100)
    content = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    category = models.ManyToManyField(Category)
    published_date = models.DateTimeField(blank=True, null=True)
    status = models.BooleanField(default=False)
    count_views = models.IntegerField(default=0)
    tags = TaggableManager()

    class Meta:
        ordering = ['-created_date']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:singleblog', kwargs={'post_id': self.id})


class Comment(models.Model):
    name = models.CharField(max_length=255)
    email = models.EmailField()
    subject = models.CharField(max_length=255)
    message = models.TextField()
    approved = models.BooleanField(default=False)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

blog/forms.py
from blog.models import Comment
from django import forms


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = '__all__'

blog/views.py
from django.http import Http404
from django.utils import timezone
from django.contrib import messages
from django.shortcuts import render, get_object_or_404
from blog.forms import CommentForm
from blog.models import Post, Comment
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage


# Create your views here.


def blog(request, **kwargs):
    posts = Post.objects.filter(status=True, published_date__lte=timezone.now())
    if kwargs.get('cat_name') is not None:
        posts = posts.filter(category__name=kwargs['cat_name'])
    if kwargs.get('author_user') is not None:
        posts = posts.filter(author__username=kwargs['author_user'])
    if kwargs.get('tag_name') is not None:
        posts = posts.filter(tags__name__in=kwargs['tag_name'])

    posts = Paginator(posts, 3)
    try:
        page_numb = request.GET.get('page')
        posts = posts.get_page(page_numb)
    except PageNotAnInteger:
        posts = posts.get_page(1)
    except EmptyPage:
        posts = posts.get_page(1)

    context = {'posts': posts}
    return render(request, 'blog/blog.html', context)


def single_blog(request, post_id):
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your Comment Sent Successfully')
        else:
            messages.error(request, 'There was an error, Please try again')
    else:
        form = CommentForm()
    posts = Post.objects.filter(status=True, published_date__lte=timezone.now())
    post = get_object_or_404(posts, pk=post_id)
    post.count_views += 1
    post.save()
    current_post = Post.objects.get(pk=post_id)
    related_posts = Post.objects.filter(status=True, published_date__lte=timezone.now())
    next_post = related_posts.filter(id__gt=current_post.id).order_by('id').first()
    prev_post = related_posts.filter(id__lt=current_post.id).order_by('-id').first()
    comments = Comment.objects.filter(approved=True, post=post.id)
    context = {
        'post': post,
        'next_post': next_post,
        'prev_post': prev_post,
        'comments': comments,
        'form': form,
    }

    return render(request, 'blog/single-blog.html', context)


def blog_search(request):
    posts = Post.objects.filter(status=True, published_date__lte=timezone.now())
    if request.method == 'GET':
        posts = posts.filter(title__contains=request.GET.get('s'))
    context = {'posts': posts}
    return render(request, 'blog/blog.html', context)

templates/blog/blog.html
{%  extends 'base.html' %}
{% load static %}
{% load blog_tag %}
{% block base %}
{% load humanize %}

        <!--================Blog Categorie Area =================-->
      {% blog_last_posts %}
        <!--================Blog Categories Area =================-->

        <!--================Blog Area =================-->
        <section class="blog_area">
            <div class="container">
                <div class="row">
                    <div class="col-lg-8">
                        <div class="blog_left_sidebar">
                            {% for post in posts %}
                            <article class="row blog_item">
                               <div class="col-md-3">
                                   <div class="blog_info text-right">
                                        <div class="post_tag">
                                        {% for tag in post.tags.all %}
                                            <a href="{% url 'blog:tag' tag_name=tag.name %}">{{ tag.name }}</a>
                                        {% endfor %}
                                        {% for cat in post.category.all %}
                                            <a href="{% url 'blog:category' cat_name=cat.name %}">{{ cat.name }}</a>{% if not forloop.last %},{% endif %}
                                        {% endfor %}
                                        </div>
                                        <ul class="blog_meta list">
                                            <li><a href="{% url 'blog:author' author_user=post.author.username %}">{{ post.author }}<i class="lnr lnr-user"></i></a></li>
                                            <li><a href="#">{{ post.created_date|naturaltime}}<i class="lnr lnr-calendar-full"></i></a></li>
                                            <li>{{ post.count_views }} Views<i class="lnr lnr-eye"></i></li>
                                            <li>{% commentcount post.id %} Comments<i class="lnr lnr-eye"></i></li>
                                        </ul>
                                    </div>
                               </div>
                                <div class="col-md-9">
                                    <div class="blog_post">
                                        <img src="{{post.image.url}}" alt="">
                                        <div class="blog_details">
                                            <a href="{% url 'blog:singleblog' post_id=post.id %}"><h2>{{ post.title }}</h2></a>
                                            <p>{{ post.content|safe|truncatewords:20 }}

                                            </p>
                                            <a href="{% url 'blog:singleblog' post_id=post.id%}" class="white_bg_btn">View More</a>
                                        </div>
                                    </div>
                                </div>
                            </article>
                            {% endfor %}
                            <nav class="blog-pagination justify-content-center d-flex">
		                        <ul class="pagination">
                                    {% if posts.has_previous %}
		                            <li class="page-item">
		                                <a href="?page={{ posts.previous_page_number }}" class="page-link" aria-label="Previous">
		                                    <span aria-hidden="true">
		                                        <span class="lnr lnr-chevron-left"></span>
		                                    </span>
		                                </a>
		                            </li>
                                    {% endif %}
                                    {% for i in posts.paginator.page_range %}
                                        {% if posts.number == i %}
		                            <li class="page-item active"><a href="?page={{ i }}" class="page-link">{{ i }}</a></li>
                                            {% else %}
		                            <li class="page-item "><a href="?page={{ i }}" class="page-link">{{ i }}</a></li>
                                        {% endif %}
                                    {% endfor %}
                                    {% if posts.has_next %}
		                            <li class="page-item">
		                                <a href="?page={{ posts.next_page_number }}" class="page-link" aria-label="Next">
		                                    <span aria-hidden="true">
		                                        <span class="lnr lnr-chevron-right"></span>
		                                    </span>
		                                </a>
		                            </li>
                                   {% endif %}
		                        </ul>
		                    </nav>
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="blog_right_sidebar">
                            {% include 'blog/tags/search_bar.html' %}
                            {% include 'blog/temp.html' %}
                            {% post_categories %}


                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!--================Blog Area =================-->
 {% endblock %}

templates/blog/single-blog.html
{%  extends 'base.html' %}
{% load static %}
{% block base %}
{% load blog_tag %}
{% load humanize %}

        <!--================Blog Area =================-->
        <section class="blog_area single-post-area p_120">
            <div class="container">
                <div class="row">
                    <div class="col-lg-8 posts-list">
                        <div class="single-post row">
                            <div class="col-lg-12">
                                <div class="feature-img">
                                    <img class="img-fluid" src="{{ post.image.url }}" alt="">
                                </div>									
                            </div>
                            <div class="col-lg-3  col-md-3">
                                <div class="blog_info text-right">
                                    <div class="post_tag">
                                        {% for tag in post.tags.all %}
                                            <a href="{% url 'blog:tag' tag_name=tag.name %}">{{ tag.name }}</a>
                                        {% endfor %}
                                        {% for cat in post.category.all %}
                                            <a href="{% url 'blog:category' cat_name=cat.name %}">{{ cat.name }}</a>{% if not forloop.last %},{% endif %}
                                        {% endfor %}

                                    </div>
                                    <ul class="blog_meta list">
                                        <li><a href="{% url 'blog:author' author_user=post.author %}">{{ post.author }}<i class="lnr lnr-user"></i></a></li>
                                        <li><a href="#">{{ post.published_date|naturaltime }}<i class="lnr lnr-calendar-full"></i></a></li>
                                        <li><a href="#">{{ post.count_views }}<i class="lnr lnr-eye"></i></a></li>
                                    </ul>
                                    <ul class="social-links">
                                        <li><a href="https://www.facebook.com/asrin.vakili"><i class="fa fa-facebook"></i></a></li>
                                        <li><a href=https://twitter.com/AsrinVakili"><i class="fa fa-twitter"></i></a></li>
                                        <li><a href="https://github.com/asrinvakili/"><i class="fa fa-github"></i></a></li>
                                    </ul>
                                </div>
                            </div>
                            <div class="col-lg-9 col-md-9 blog_details">
                                <h2>{{ post.title }}</h2>
                                <p >
                                    {{ post.content|safe }}
                                </p>

                            </div>
                        <div class="navigation-area">
                            <div class="row">
                                <div class="col-lg-6 col-md-6 col-12 nav-left flex-row d-flex justify-content-start align-items-center">
                                    {% if prev_post %}
                                    <div class="thumb">
                                        <a href="{% url 'blog:singleblog' post_id=prev_post.id %}"><img class="img-fluid" src="{{ prev_post.image.url }}" alt=""></a>
                                    </div>
                                    <div class="arrow">
                                        <a href="{% url 'blog:singleblog' post_id=prev_post.id %}"><span class="lnr text-white lnr-arrow-left"></span></a>
                                    </div>
                                    <div class="detials">
                                        <p>Prev Post</p>
                                        <a href="{% url 'blog:singleblog' post_id=prev_post.id %}"><h4>{{ prev_post.title }}</h4></a>
                                    </div>
                                    {% endif %}
                                </div>
                                <div class="col-lg-6 col-md-6 col-12 nav-right flex-row d-flex justify-content-end align-items-center">
                                    {% if next_post %}
                                    <div class="detials">
                                        <p>Next Post</p>
                                        <a href="{% url 'blog:singleblog' post_id=next_post.id %}"><h4>{{ next_post.title }}</h4></a>
                                    </div>
                                    <div class="arrow">
                                        <a href="{% url 'blog:singleblog' post_id=next_post.id %}"><span class="lnr text-white lnr-arrow-right"></span></a>
                                    </div>
                                    <div class="thumb">
                                        <a href="{% url 'blog:singleblog' post_id=next_post.id %}"><img class="img-fluid" src="{{ next_post.image.url }}" alt=""></a>
                                    </div>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                        </div>
                        <div class="comments-area">
                            <h4>{{ comments|length }} Comments</h4>
                            <div class="comment-list">
                                <div class="single-comment justify-content-between d-flex">
                                    {% for comment in comments %}
                                    <div class="user justify-content-between d-flex">
                                        <div class="desc">
                                            <h5><a href="#">{{ comment.name }}</a></h5>
                                            <p class="date">{{ comment.created_date|naturaltime }} </p>
                                            <p class="comment">
                                                {{ comment.message|truncatewords:4 }}
                                            </p>
                                        </div>
                                    </div>
                                    {% empty %}
                                        <p>No Comments</p>
                                    {% endfor %}
                                </div>
                            </div>
                        </div>
                        <div class="comment-form">
                            <h4>Leave a Comment</h4>
                            <form action="{% url 'blog:singleblog' post_id=post.id %}" method="post">
                                {% csrf_token %}

                                <div class="form-group form-inline">
                                    <div >
                                      <input type="hidden" name="post" value="{{ post.id }}">
                                  </div>
                                  <div class="form-group col-lg-6 col-md-6 name">
                                      <label>
                                      <input type="text" class="form-control"  placeholder="Enter Name" name="name">
                                  </label>
                                  </div>
                                  <div class="form-group col-lg-6 col-md-6 email">
                                      <label>
                                      <input type="email" class="form-control" name="email" placeholder="Enter Email">
                                  </label>
                                  </div>
                                </div>
                                <div class="form-group">
                                    <label>
                                    <input type="text" name="subject" class="form-control" placeholder="Subject">
                                </label>
                                </div>
                                <div class="form-group">
                                    <label>
                                        <textarea placeholder="Message..." class="form-control mb-10" rows="5" name="message" ></textarea>
                                    </label>
                                </div>
                                <input type="submit" value="Submit" >
                            </form>
                        </div>
                    </div>
                        <div class="col-lg-4">
                            <div class="blog_right_sidebar">
                                {% include 'blog/tags/search_bar.html' %}
                                 {% include 'blog/temp.html' %}
                                {% last_post %}
                                {% post_categories %}
                           </div>

                        </div>
                    </div>

             </div>
        </section>
        <!--================Blog Area =================-->
 {% endblock %}

templates/blog/temp.html
{% load blog_tag %}
{% load static %}

                            <aside class="single_sidebar_widget author_widget">
                                <img class="author_img rounded-circle" src="{% static 'img/blog/pro.png' %}" alt="">
                                <h4>{{ name }}</h4>
                                <p>Senior blog writer</p>
                                <div class="social_icon">
                                    <a href="https://www.facebook.com/asrin.vakili"><i class="fa fa-facebook"></i></a>
                                    <a href="https://twitter.com/AsrinVakili"><i class="fa fa-twitter"></i></a>
                                    <a href="https://github.com/asrinvakili/"><i class="fa fa-github"></i></a>
                                </div>
                                <p>Hello. I am Asrin Vakili. I like to write about my interests and hobbies. You can see the topics I have written on my blog.</p>
                                <div class="br"></div>
                            </aside>
                            <aside class="single-sidebar-widget tag_cloud_widget">
                                <h4 class="widget_title">Tag Clouds</h4>
                                <ul class="list">

                                    {% for tag in post.tags.all %}
                                    <li><a href="{% url 'blog:tag' tag_name=tag.name %}">{{ tag.name }}</a></li>
                                    {% endfor %}

                                </ul>
                            </aside>