CVwebsite/urls.py
from blog.feeds import LatestEntriesFeed
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import path, include
from home.sitemap import StaticViewSitemap

sitemaps = {'static': StaticViewSitemap, }

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('about/', include('about.urls')),
    path('contact/', include('contact.urls')),
    path('blog/', include('blog.urls')),
    path('accounts/', include('allauth.urls')),
    path('robots.txt', include('robots.urls'), ),
    path('rss/feed/', LatestEntriesFeed()),
    path('summernote/', include('django_summernote.urls'), ),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += [
    path('captcha/', include('captcha.urls')),
]

about/urls.py
from django.urls import path
from about.views import about

app_name = 'about'

urlpatterns = [
    path('', about, name='aboutUs'),
]

blog/urls.py
from django.urls import path

from blog.views import blog, single_blog
from blog.sitemap import BlogSitemap

sitemaps = {'blog': BlogSitemap}
app_name = 'blog'

urlpatterns = [
    path('', blog, name='weblog'),
    path('<int:post_id>/', single_blog, name='singleblog'),
    path('category/<str:cat_name>/', blog, name='category'),
    path('author/<str:author_user>/', blog, name='author'),
    path('search/', blog, name='search'),

    path('tag/<str:tag_name>/', blog, name='tag'),
]

contact/urls.py
from django.urls import path
from contact.views import contact, news_view

app_name = 'contact'

urlpatterns = [
    path('', contact, name='contactUs'),
    path('newsletter', news_view, name='news'),

]

home/urls.py
from django.urls import path
from home.views import index

app_name = 'home'

urlpatterns = [
    path('', index, name='index'),
]

blog/models.py
from audioop import reverse
from taggit.managers import TaggableManager
from django.db import models
from django.contrib.auth.models import User


# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=100, null=True)

    def __str__(self):
        return self.name


class Post(models.Model):
    image = models.ImageField(upload_to='blog/', default='blog/default.jpg')
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    title = models.CharField(max_length=100)
    content = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    category = models.ManyToManyField(Category)
    published_date = models.DateTimeField(blank=True, null=True)
    status = models.BooleanField(default=False)
    count_views = models.IntegerField(default=0)
    tags = TaggableManager()

    class Meta:
        ordering = ['-created_date']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:singleblog', kwargs={'post_id': self.id})


class Comment(models.Model):
    name = models.CharField(max_length=255)
    email = models.EmailField()
    subject = models.CharField(max_length=255)
    message = models.TextField()
    approved = models.BooleanField(default=False)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

contact/models.py
from django.db import models


# Create your models here.
class Contact(models.Model):
    name = models.CharField(max_length=100, default="Unknown")
    subject = models.CharField(max_length=100, null=True, blank=True)
    email = models.EmailField()
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class NewsLetter(models.Model):
    email = models.EmailField()

    def __str__(self):
        return self.email

blog/forms.py
from blog.models import Comment
from django import forms


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = '__all__'

contact/forms.py
from django import forms
from captcha.fields import CaptchaField
from contact.models import Contact, NewsLetter


class contact_form(forms.ModelForm):
    captcha = CaptchaField()
    class Meta:
        model = Contact
        fields = '__all__'


class NewsLetterForm(forms.ModelForm):
    class Meta:
        model = NewsLetter
        fields = '__all__'

blog/views.py
from django.http import Http404
from django.utils import timezone
from django.contrib import messages
from django.shortcuts import render, get_object_or_404
from blog.forms import CommentForm
from blog.models import Post, Comment
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage


# Create your views here.


def blog(request, **kwargs):
    posts = Post.objects.filter(status=True, published_date__lte=timezone.now())
    if kwargs.get('cat_name') is not None:
        posts = posts.filter(category__name=kwargs['cat_name'])
    if kwargs.get('author_user') is not None:
        posts = posts.filter(author__username=kwargs['author_user'])
    if kwargs.get('tag_name') is not None:
        posts = posts.filter(tags__name__in=kwargs['tag_name'])

    posts = Paginator(posts, 3)
    try:
        page_numb = request.GET.get('page')
        posts = posts.get_page(page_numb)
    except PageNotAnInteger:
        posts = posts.get_page(1)
    except EmptyPage:
        posts = posts.get_page(1)

    context = {'posts': posts}
    return render(request, 'blog/blog.html', context)


def single_blog(request, post_id):
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your Comment Sent Successfully')
        else:
            messages.error(request, 'There was an error, Please try again')
    else:
        form = CommentForm()
    posts = Post.objects.filter(status=True, published_date__lte=timezone.now())
    post = get_object_or_404(posts, pk=post_id)
    post.count_views += 1
    post.save()
    current_post = Post.objects.get(pk=post_id)
    related_posts = Post.objects.filter(status=True, published_date__lte=timezone.now())
    next_post = related_posts.filter(id__gt=current_post.id).order_by('id').first()
    prev_post = related_posts.filter(id__lt=current_post.id).order_by('-id').first()
    comments = Comment.objects.filter(approved=True, post=post.id)
    context = {
        'post': post,
        'next_post': next_post,
        'prev_post': prev_post,
        'comments': comments,
        'form': form,
    }

    return render(request, 'blog/single-blog.html', context)


def blog_search(request):
    posts = Post.objects.filter(status=True, published_date__lte=timezone.now())
    if request.method == 'GET':
        posts = posts.filter(title__contains=request.GET.get('s'))
    context = {'posts': posts}
    return render(request, 'blog/blog.html', context)

contact/views.py
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.shortcuts import render
from contact.forms import contact_form, NewsLetterForm


# Create your views here.
def contact(request):
    if request.method == 'POST':
        form = contact_form(request.POST)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.name = 'Unknown'
            instance.save()
            messages.success(request, "Thank you for contacting us.")
        else:
            messages.error(request, "Please correct the errors.")
    else:
        form = contact_form()

    return render(request, 'contact.html', {'form': form})


def news_view(request):
    if request.method == 'POST':
        form = NewsLetterForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your Email Submitted Successfully')
            return HttpResponseRedirect('/')
        else:
            messages.error(request, 'There was an error, Please try again')

templates/about-us.html
{%  extends 'base.html' %}
{% load static %}
{% block base %}
        <!--================Home Banner Area =================-->
        <section class="profile_area">
           	<div class="container">
           		<div class="profile_inner p_120">
					<div class="row">
						<div class="col-lg-5">
							<img class="img-fluid" src="{% static 'img/asrin-2.jpg' %}" alt="">
						</div>
						<div class="col-lg-7">
							<div class="personal_text">
								<h6>junior python developer</h6>
								<h3>{{ name }}</h3>
								<h4>{{ education }}</h4>
								<p>{{ bio1 }}</p>
                                <p>{{ bio3 }}</p>
                                <p>{{ bio2 }}</p>

							</div>
						</div>
					</div>
           		</div>
            </div>
        </section>
        <!--================End Home Banner Area =================-->
        
        <!--================Welcome Area =================-->
        <section class="welcome_area p_120">
        	<div class="container">
        		<div class="row welcome_inner">
        				<div class="col-lg-6">
        				<div class="tools_expert">
        					<div class="skill_main">
								<div class="skill_item">
									<h4>Python <span class="counter">80</span>%</h4>
									<div class="progress_br">
										<div class="progress">
											<div class="progress-bar" role="progressbar" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100"></div>
										</div>
									</div>
								</div>
								<div class="skill_item">
									<h4>Java <span class="counter">60</span>%</h4>
									<div class="progress_br">
										<div class="progress">
											<div class="progress-bar" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100"></div>
										</div>
									</div>
								</div>
								<div class="skill_item">
									<h4>Html <span class="counter">100</span>%</h4>
									<div class="progress_br">
										<div class="progress">
											<div class="progress-bar" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100"></div>
										</div>
									</div>
								</div>
								<div class="skill_item">
									<h4>CSS <span class="counter">50</span>%</h4>
									<div class="progress_br">
										<div class="progress">
											<div class="progress-bar" role="progressbar" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100"></div>
										</div>
									</div>
								</div>
								<div class="skill_item">
									<h4>Assembly <span class="counter">85</span>%</h4>
									<div class="progress_br">
										<div class="progress">
											<div class="progress-bar" role="progressbar" aria-valuenow="85" aria-valuemin="0" aria-valuemax="100"></div>
										</div>
									</div>
								</div>
							</div>
        				</div>
        			</div>
        			<div class="col-lg-6">
        				<div class="tools_expert">
        					<div class="skill_main">
								<div class="skill_item">
									<h4>After Effects <span class="counter">65</span>%</h4>
									<div class="progress_br">
										<div class="progress">
											<div class="progress-bar" role="progressbar" aria-valuenow="65" aria-valuemin="0" aria-valuemax="100"></div>
										</div>
									</div>
								</div>
								<div class="skill_item">
									<h4>Photoshop <span class="counter">80</span>%</h4>
									<div class="progress_br">
										<div class="progress">
											<div class="progress-bar" role="progressbar" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100"></div>
										</div>
									</div>
								</div>
								<div class="skill_item">
									<h4>Illustrator <span class="counter">85</span>%</h4>
									<div class="progress_br">
										<div class="progress">
											<div class="progress-bar" role="progressbar" aria-valuenow="85" aria-valuemin="0" aria-valuemax="100"></div>
										</div>
									</div>
								</div>
								<div class="skill_item">
									<h4>blender <span class="counter">75</span>%</h4>
									<div class="progress_br">
										<div class="progress">
											<div class="progress-bar" role="progressbar" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100"></div>
										</div>
									</div>
								</div>
								<div class="skill_item">
									<h4>Calligraphy <span class="counter">100</span>%</h4>
									<div class="progress_br">
										<div class="progress">
											<div class="progress-bar" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100"></div>
										</div>
									</div>
								</div>
							</div>
        				</div>
        			</div>
        		</div>
        	</div>
        </section>
        <!--================End Welcome Area =================-->
        
        <!--================Testimonials Area =================-->
        <section class="testimonials_area p_120">
        	<div class="container">
        		<div class="main_title">
        			<h2>Certificate</h2>
        			<p>The certificates of completion of the educational courses that I have completed can be seen below.</p>
        		</div>
        		<div class="testi_inner">
					<div class="testi_slider owl-carousel">
						<div class="item">
							<div class="g_img_item">
        						<img class="img-fluid" src="{% static 'img/madrak/m1.jpg' %}" alt="">
        					</div>
						</div>
						<div class="item">
							<div class="g_img_item">
        						<img class="img-fluid" src="{% static 'img/madrak/m2.jpg' %}" alt="">
        					</div>
						</div>
						<div class="item">
							<div class="g_img_item">
        						<img class="img-fluid" src="{% static 'img/madrak/m3.jpg' %}" alt="">
        					</div>
						</div>
					</div>
        		</div>
        	</div>
        </section>
        <!--================End Testimonials Area =================-->
 {% endblock %}

templates/base.html
{% load compress %}
{% load static %}
{% load socialaccount %}
<!Doctype html>
<html lang="en">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <title>Asrin Vakili</title>
        {% compress css %}
        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
        <link rel="stylesheet" href="{% static 'vendors/linericon/style.css' %}">
        <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
        <link rel="stylesheet" href="{% static 'vendors/owl-carousel/owl.carousel.min.css' %}">
        <link rel="stylesheet" href="{% static 'vendors/lightbox/simpleLightbox.css' %}">
        <link rel="stylesheet" href="{% static 'vendors/nice-select/css/nice-select.css' %}">
        <link rel="stylesheet" href="{% static 'vendors/animate-css/animate.css' %}">
        <link rel="stylesheet" href="{% static 'vendors/popup/magnific-popup.css' %}">
        <link rel="stylesheet" href="{% static 'vendors/flaticon/flaticon.css' %}">
        {% endcompress %}
        {% compress css %}   
        <!-- main css -->
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
        <link rel="stylesheet" href="{% static 'css/responsive.css' %}">
        {% endcompress %}
    </head>
    <body>

        <!--================Header Menu Area =================-->
        <header class="header_area">
            <div class="main_menu">
            	<nav class="navbar navbar-expand-lg navbar-light">
					<div class="container box_1620">
                        <ul class="nav navbar-nav menu_nav ml-auto">
                        {% if request.user.is_authenticated %}
                            <li class="nav-item active"><a class="nav-link" href="#">Welcome {{ user.username }}</a></li>
                            <li class="nav-item"><a class="nav-link" href="{% url 'account_logout' %}">Logout</a></li>
                        <!--<a class="navbar-brand logo_h" href="index.html"><p>login</p></a>
                        <a class="navbar-brand logo_h" href="index.html"><p>logout</p></a>-->
                        {% else %}
                            <li class="nav-item active"><a class="nav-link" href="{% url 'account_login' %}">Login</a></li>
                        {% endif %}
                        </ul>
						<!-- Collect the nav links, forms, and other content for toggling -->
						<div class="collapse navbar-collapse offset" id="navbarSupportedContent">
							<ul class="nav navbar-nav menu_nav ml-auto">
								<li class="nav-item active"><a class="nav-link" href="{% url 'home:index' %}">Home</a></li>
								<li class="nav-item"><a class="nav-link" href="{% url 'about:aboutUs' %}">About</a></li>
								<li class="nav-item"><a class="nav-link" href="{% url 'blog:weblog' %}">Blog</a></li>
								<li class="nav-item"><a class="nav-link" href="{% url 'contact:contactUs' %}">Contact</a></li>
							</ul>
						</div>
					</div>
            	</nav>
            </div>
        </header>
        <!--================Header Menu Area =================-->

        <!--================Home Banner Area =================-->
        <section class="home_banner_area">
           	<div class="container box_1620">
           		<div class="banner_inner d-flex align-items-center">
					<div class="banner_content">
						<div class="media">
							<div class="d-flex">
								<img src="{% static 'img/asrin.jpg' %}" alt="Asrin Vakili">
							</div>
							<div class="media-body">
								<div class="personal_text">
									<h6>Hello Everybody, i am</h6>
									<h3>Asrin Vakili</h3>
									<h4>Junior Python Developer</h4>
									<p>I'm junior Django developer, starting pytho about 4 years ago. This website is a CV website I created to Django project.</p>
									<ul class="list basic_info">
										<li><a href="#"><i class="lnr lnr-calendar-full"></i> 30st April, 1991</a></li>
										<li><a href="#"><i class="lnr lnr-phone-handset"></i> +98 9302392924 </a></li>
										<li><a href="#"><i class="lnr lnr-envelope"></i> asrin_vakili@yahoo.com</a></li>
										<li><a href="#"><i class="lnr lnr-home"></i> Kurdistan, Saqqez</a></li>
									</ul>
									<ul class="list personal_social">
										<li><a href="https://www.facebook.com/asrin.vakili"><i class="fa fa-facebook"></i></a></li>
										<li><a href="https://twitter.com/AsrinVakili"><i class="fa fa-twitter"></i></a></li>
										<li><a href="https://www.linkedin.com/in/asrin-vakili/"><i class="fa fa-linkedin"></i></a></li>
									</ul>
								</div>
							</div>
						</div>
					</div>
				</div>
            </div>
        </section>
        <div id="messages">
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }}">
                {{ message }}
            </div>
        {% endfor %}
        </div>
        <!--================End Home Banner Area =================-->

    {% block base %}

    {% endblock %}


       <!--================Footer Area =================-->
        <footer class="footer_area p_120">
        	<div class="container">
        		<div class="row footer_inner">
        			<div class="col-lg-5 col-sm-6">
        				<aside class="f_widget ab_widget">
        					<div class="f_title">
        						<h3>About Me</h3>
        					</div>
        					<p>Do you want to be even more successful? Learn to love learning and growth. The more effort you put into improving your skills,</p>
        				</aside>
        			</div>
        			<div class="col-lg-5 col-sm-6">
        				<aside class="f_widget news_widget">
        					<div class="f_title">
        						<h3>Newsletter</h3>
        					</div>
        					<p>Stay updated with our latest trends</p>
        					<div >
                                <form target="_blank" action="{% url 'contact:news' %}" method="post" >
                                    {% csrf_token %}
                                	<div class="input-group d-flex flex-row">
                                        <label>
                                            <input name="email"  required="" type="email" autocomplete="Your Email">
                                        </label>
                                        <button type="submit"><span class="lnr lnr-arrow-right"></span></button>
                                    </div>
                                    <div class="mt-10 info"></div>
                                </form>
                            </div>
        				</aside>
        			</div>
        			<div class="col-lg-2">
        				<aside class="f_widget social_widget">
        					<div class="f_title">
        						<h3>Follow Me</h3>
        					</div>
        					<p>Let us be social</p>
        					<ul class="list">
        						<li><a href="https://www.facebook.com/asrin.vakili"><i class="fa fa-facebook"></i></a></li>
                                <li><a href="https://twitter.com/AsrinVakili"><i class="fa fa-twitter"></i></a></li>
                                <li><a href="https://www.linkedin.com/in/asrin-vakili/"><i class="fa fa-linkedin"></i></a></li>
        					</ul>
        				</aside>
        			</div>
        		</div>
        	</div>
        </footer>
        <!--================End Footer Area =================-->






        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        {% compress js %}
        <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
        <script src="{% static 'js/popper.js' %}"></script>
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
        <script src="{% static 'js/stellar.js' %}"></script>
        <script src="{% static 'vendors/lightbox/simpleLightbox.min.js' %}"></script>
        <script src="{% static 'vendors/nice-select/js/jquery.nice-select.min.js' %}"></script>
        <script src="{% static 'vendors/isotope/imagesloaded.pkgd.min.js' %}"></script>
        <script src="{% static 'vendors/isotope/isotope.pkgd.min.js' %}"></script>
        <script src="{% static 'vendors/owl-carousel/owl.carousel.min.js' %}"></script>
        <script src="{% static 'vendors/popup/jquery.magnific-popup.min.js' %}"></script>
        <script src="{% static 'js/jquery.ajaxchimp.min.js' %}"></script>
        <script src="{% static 'vendors/counter-up/jquery.waypoints.min.js' %}"></script>
        <script src="{% static 'vendors/counter-up/jquery.counterup.min.js' %}"></script>
        <script src="{% static 'js/mail-script.js' %}"></script>
        <script src="{% static 'js/theme.js' %}"></script>
        {% endcompress %}
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>


    </body>
</html>

templates/contact.html
{%  extends 'base.html' %}
{% load static %}
{% block base %}
        <!--================Contact Area =================-->
        <section class="contact_area p_120">
            <div class="container">

                <div class="row">
                    <div class="col-lg-3">
                        <div class="contact_info">
                            <div class="info_item">
                                <i class="lnr lnr-home"></i>
                                <h6>Iran, Kurdistan, Saqqez</h6>
                                <p>Saqqez</p>
                            </div>
                            <div class="info_item">
                                <i class="lnr lnr-phone-handset"></i>
                                <h6><a href="#">+98 930 239 2924</a></h6>
                                <p>Mon to Fri 9am to 6 pm</p>
                            </div>
                            <div class="info_item">
                                <i class="lnr lnr-envelope"></i>
                                <h6><a href="#">asrin_vakili@yahoo.com</a></h6>
                                <p>Send us your query anytime!</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-9">
                        <form class="row contact_form" action="{% url 'contact:contactUs' %}" method="post"  novalidate="novalidate">
                            {% csrf_token %}
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="name"></label><input type="text" class="form-control" id="name" name="name" placeholder="Enter your name">
                                </div>
                                <div class="form-group">
                                    <label for="email"></label><input type="email" class="form-control" id="email" name="email" placeholder="Enter email address">
                                </div>
                                <div class="form-group">
                                    <label for="subject"></label><input type="text" class="form-control" id="subject" name="subject" placeholder="Enter Subject">
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="message"></label><textarea class="form-control" name="message" id="message" rows="1" placeholder="Enter Message"></textarea>
                                </div>

                            <div class="col-md-12 text-right">
                                <div class="pb-3">
                                {{form.captcha}}
                                </div>
                                <button type="submit" value="submit" class="btn submit_btn">Send Message</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </section>
        <!--================Contact Area =================-->

        
        <!--================Contact Success and Error message Area =================-->
        <div id="success" class="modal modal-message fade" role="dialog">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <i class="fa fa-close"></i>
                        </button>
                        <h2>Thank you</h2>
                        <p>Your message is successfully sent...</p>
                    </div>
                </div>
            </div>
        </div>

        <!-- Modals error -->

        <div id="error" class="modal modal-message fade" role="dialog">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <i class="fa fa-close"></i>
                        </button>
                        <h2>Sorry !</h2>
                        <p> Something went wrong </p>
                    </div>
                </div>
            </div>
        </div>
        <!--================End Contact Success and Error message Area =================-->
        
        
        
{% endblock %}